name: ci-cd

on:
  push:
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Coursier cache
        uses: coursier/cache-action@v5

      - name: test
        run: sbt test

      - name: test-coverage
        # TODO: Use coveralls
        run: echo "test coverage"
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: mutation test
        # TODO: Use stryker
        run: echo "mutation test"

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Coursier cache
        uses: coursier/cache-action@v5

      - name: compile
        run: sbt Test/compile

  deploy:
    runs-on: ubuntu-latest

    on:
      push:
        branches: [ main ]
        tags: [ "*" ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Coursier cache
        uses: coursier/cache-action@v5

      - name: publish staging
        # TODO: publish to staging sonatype
        run: sbt publishLocal
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        if: startsWith(github.ref, 'refs/tags/') != true

      - name: publish production
        # TODO: publish to production sonatype
        run: sbt publishLocal
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        if: startsWith(github.ref, 'refs/tags/v')

  clean_up:
    runs-on: ubuntu-latest

    steps:
      - name: clean-up
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
