name: ci-cd

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: test
        run: sbt test

      - name: test-coverage
        # TODO: Use coveralls
        run: echo "test coverage"
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: mutation test
        # TODO: Use stryker
        run: echo "mutation test"
        if: github.ref == 'refs/heads/main'

  deploy:
    runs-on: ubuntu-latest

    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v1

      - name: publish staging
        # TODO: publish to staging sonatype
        run: sbt publishLocal
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        if: startsWith(github.ref, 'refs/tags/') != true

      - name: publish production
        # TODO: publish to production sonatype
        run: sbt publishLocal
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        if: startsWith(github.ref, 'refs/tags/v')
