name: ci-cd

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: test
        run: sbt test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: detailed test reporting
        uses: dorny/test-reporter@v1
        if: always()
        with:
          list-suites: "all"
          list-tests: "all"
          max-annotations: 10
          fail-on-error: true
          name: Detailed Unit Tests Reporting
          path: "target/test-reports/*.xml"
          reporter: java-junit

      - name: basic test reporting
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "target/test-reports/*.xml"
          check_name: Basic Unit Tests Reporting
          comment_title: Tests Report
          time_unit: seconds
          job_summary: false

      - name: test coverage
        # TODO: Use coveralls
        run: echo "test coverage"
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: mutation test
        # TODO: Use stryker
        run: echo "mutation test"
        if: github.ref == 'refs/heads/main'

  deploy:
    runs-on: ubuntu-latest

    needs: test
    if: github.ref == 'refs/heads/main'

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: publish staging
        run: sbt 'set isSnapshot := true' publish
        if: startsWith(github.ref, 'refs/tags/') != true

      - name: publish production
        run: sbt publish
        if: startsWith(github.ref, 'refs/tags/v')
